let resumePackage = {
  resumeSiteUid: "20200325153742558U00000000404924",
  siteOrganizationName: "登录账号对应公司名称",
  resumes: [
    {
      resumeId: "eylZFVOciNPE0PtJqWH6X(h3zLCzSGxB",
      name: "何晓青",
      sexName: "女",
      birthday: "1995/9/01",
      age: "26",
      mobile: "17721330908",
      email: "2498146123@qq.com",
      marriedName: 0,
      registerAddress: "四川 南充",
      zipCode: "",
      regionName: "上海 宝山区",
      workName: "7",
      educationName: "大专",
      contactAddress: "上海 宝山区",
      releaseCityName: "上海",
      workArea: "上海",
      workAddress: "蕰川路6号",
      applyPosition: "前台接待",
      jobIntentionInfo: "前台/总机/接待,行政专员",
      jobTypeName: "全职,全职",
      objectiveJob: "行政专员",
      jobIndustry: "电子商务、广告业、文化艺术/娱乐,互联网、通信/网络设备",
      jobPlace: "上海",
      expectSalaryName: "5千-6千",
      dutyTimeName: "在职-正在找工作",
      introduction:
        "虚心好学、待人热情、工作细心，能够熟练掌握word,Excel.PPT等常用办公软件,认真负责,适应力强，吃苦耐劳，敢于迎接新挑战",
      educationExperienceList: [
        {
          startDate: "2017/09/01",
          endDate: "2020/07/01",
          school: "上海应用技术大学",
          major: "其他",
          educationName: "大专",
        },
      ],
      workExperienceList: [
        {
          startDate: "2018/04/01",
          endDate: "",
          workUnit: "上海姜饼信息科技有限公司",
          position: "总监助理",
          companyIndustryName: "",
          companyNutureName: "",
          companyScaleName: "",
          jobContent:
            "1.负责协助主管或经理完成日常工作，准备会议文件等\n2.根据公司领导要求，传达相关通知\n3.在节假日负责公司礼品的订购,分发\n4.整理公司档案，员工手册的管理等\n5.负责日常的考勤情况，员工请假,调休,外出工作等安排和登记工作\n6.根据公司宣传工作的中心任务或重点项目，进行相关的文案策划，撰写策划文案\n7.负责编写公司对内在文件,宣传资料,ppt及总经理需要的其他公文",
        },
        {
          startDate: "2015/04/01",
          endDate: "2018/03/01",
          workUnit: "上海企炬广告传媒有限公司",
          position: "前台/总机/接待",
          companyIndustryName: "",
          companyNutureName: "",
          companyScaleName: "",
          jobContent:
            "1.负责前台电话接听转接\n2.对来访客人做好接待、登记、引导工作\n3.负责公司快递的收发工作\n4.完成领导交办的其他工作任务",
        },
      ],
      projectExperienceList: [],
      trainingExperience: "",
      previewCompany: "上海姜饼信息科技有限公司",
      major: "其他",
      school: "上海应用技术大学",
      certificates: "",
      graduatesInfo: "",
      socialEvents: "",
      languageAbility: "",
      personSkill: "",
      interest: "",
      sendTime: "2021/09/19",
    },
  ],
};
